# Generated by Django 5.0.6 on 2024-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="emp_salary",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emp_id",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
